name: CI/CD

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
      
      - name: Get Version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
      
      - name: Zip dist Directory
        run: |
          cd dist
          zip -r ../module.zip ./*
      
      
      - name: Update Latest Release
        id: update_latest_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json,./module.zip'
          tag: latest
      
      - name: Create Version Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json,./module.zip'
          tag: ${{ steps.get_version.outputs.version }}